version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: my_weight
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql

