default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: my_weight_development
  username: my_weight
  password:
  host: localhost
  port: 5432
  schema_search_path: public
  min_messages: notice

test:
  <<: *default
  database: my_weight_test

production:
  <<: *default
  database: my_weight_production
  username: my_weight
  password: <%= ENV['MY_WEIGHT_DATABASE_PASSWORD'] %>
