default: &default
  adapter: postgresql
  encoding: utf8
  username: my_weight
  host: 127.0.0.1
  port: 15432
  password: root
  pool: 5

development:
  <<: *default
  database: my_weight_development
  schema_search_path: public
  min_messages: notice

test:
  <<: *default
  database: my_weight_test

production:
  <<: *default
  database: my_weight_production
  username: my_weight
  password: <%= ENV['MY_WEIGHT_DATABASE_PASSWORD'] %>
